### ISSUE TITLE
The example listed on the BasicUsage page does not work as advertised

### ISSUE THREAD

**Issue by restagner** [tednaleid/build-test-data#47]
I followed the steps outlined on the [BasicUsage](https://github.com/tednaleid/build-test-data/wiki/BasicUsage) page, but when I attempted to run 

```groovy
def a = Author.build()
println "First Name: $a.firstName"
println "Last Name: $a.lastName"
println "Author ID: $a.id"
```

from the **grails console**, the following exception is thrown

```text
Exception thrown

groovy.lang.MissingPropertyException: No such property: Author for class: ConsoleScript4
	at ConsoleScript4.run(ConsoleScript4:3)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)

```

After altering the Groovy code to include the fully qualified path to the `Author` class

```groovy
def a = grails.bookstore.example.Author.build()
println "First Name: $a.firstName"
println "Last Name: $a.lastName"
println "Author ID: $a.id"
```

It worked!!!  What am I missing? Should the fully qualified path be a requirement?

**Comment by tednaleid** [comment]
Old versions of grails didn't require domain classes to be in a package.  I've put the explicit package on the instructions now and added the import to remove any ambiguity.  Thanks.
