### ISSUE TITLE
Run executeQuery failed when execute integration test

### ISSUE THREAD

**Issue by eduardofb** [tednaleid/build-test-data#50]
I have a method in a service using a executeQuery("HQL"), but when my test call the service method throws an exception like that:

```String-based queries like [executeQuery] are currently not supported in this implementation of GORM. Use criteria instead.```

But, if I remove the annotation ```@Build``` of my test class the test pass alright.

* I'm using the 2.2.3 grails/plugin version.

**Comment by longwa** [comment]
@Build is only used for Unit tests and should not be used in integration tests. For an integration test, you don't have to enumerate which domain classes to build as the entire domain model is loaded when the environment bootstraps.

Try removing the @Build and see what happens.

**Comment by eduardofb** [comment]
RADME file says:

*This plugin is focused on creating test data for integration testing.* 

Maybe i miss something. 

But how i said before, if i remove the @Build annotations the test works fine.

Thanks for reply.

**Comment by longwa** [comment]
Sorry if the documentation wasn't clear. Build test data is intended for both unit and integration testing, just the @Build annotation is not required for integration testing. @Build is just a wrapper for @Mock, which causes Grails to use the Mock datastore, session, etc.

Integration tests work in what is essentially a fully functional Grails environment, so build-test-data doesn't require any additional annotations such as @Build. In a unit test environment, domain objects must be registered individually (using @Mock, for example, if you are not using BTD).

In both cases, the usability of the build-test-data is the same.

We should probably remove the word "integration" from the README as BTD is used for both unit and integration tests for some time now.

Glad you got it working.

**Comment by groovyGuy** [comment]
I also ran into this, not realizing that @Build is a wrapper for @Mock. I recognize that this is listed deeper in the documentation, but maybe you could mention this specifically in your wiki. It would have saved me a lot of time. Thank you! https://github.com/longwa/build-test-data/wiki
