### ISSUE TITLE
Causing NullPointerException in integration test on Grails 2.4.4

### ISSUE THREAD

**Issue by froilan** [tednaleid/build-test-data#51]
Whenever I add the Build annotation in my integration tests, my service calls suddenly throws NullPointerException.

Is this because of spock?

It is working well on unit tests.

**Comment by tednaleid** [comment]
the `@Build` annotation is only used in unit tests.  In integration tests, all domain objects get `build` automatically.  It causes problems (as you've seen) if you have `@Build` annotations on domain objects in integration tests.  Take it off and you should still be able to build and have things work.

It should also work fine with Spock tests.
